{% set version = "0.8.1" %}

package:
  name: nitime
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nitime/nitime-{{ version }}.tar.gz
  sha256: 269eae522f613c9ca8c3d62b66074a76b40d9484f468b4b8525f7c9342e96341

build:
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - scipy
    - matplotlib-base
    - networkx
    - nibabel

test:
  imports:
    - nitime
    - nitime.algorithms
    - nitime.algorithms.tests
    - nitime.analysis
    - nitime.analysis.tests
    - nitime.fmri
    - nitime.fmri.tests
    - nitime.tests

about:
  home: http://nipy.org/nitime
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Timeseries analysis for neuroscience data'

extra:
  recipe-maintainers:
    - arokem
    - ocefpaf
