{% set name = "nitime" %}
{% set version = "0.10.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: "342696afb66a2f55d5d107d40fee3e627df73757023f7de26f9a09f753ad24b5"

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [ppc64le]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - setuptools_scm
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - cython
    - numpy
    - setuptools_scm
    - pip
  run:
    - python
    - matplotlib-base
    - networkx
    - nibabel
    - scipy
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - nitime
    - nitime.algorithms
    - nitime._utils  # Verify the compiled module is available
  commands:
    - pip check
    - pytest --pyargs nitime
  requires:
    - pip
    - pytest

about:
  home: http://nipy.org/nitime
  summary: 'Nitime: timeseries analysis for neuroscience data'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - arokem
    - ocefpaf
    - effigies
