{% set name = "nitime" %}
{% set version = "0.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nitime-{{ version }}.tar.gz
  sha256: 6e7d90adbb1fa942629bce2f1f9b6de53ea1dd8b0602582ef4608c88d4343874

build:
  number: 2
  skip: true   # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - numpy
    - pip
  run:
    - python
    - cython
    - setuptools
    - matplotlib-base
    - networkx
    - nibabel
    - scipy
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - nitime
    - nitime.algorithms
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://nipy.org/nitime
  summary: 'Nitime: timeseries analysis for neuroscience data'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - arokem
    - ocefpaf
