{% set version = "0.7" %}

package:
  name: nitime
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nitime/nitime-{{ version }}.tar.gz
  sha256: 18bac8d62686f884f1ac8b8d4fdb3d644e38a8a6ece76073a576080bafcbc5e9

build:
  number: 1002
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - scipy
    - matplotlib
    - networkx
    - nibabel

test:
  imports:
    - nitime
    - nitime.algorithms
    - nitime.algorithms.tests
    - nitime.analysis
    - nitime.analysis.tests
    - nitime.fmri
    - nitime.fmri.tests
    - nitime.tests

about:
  home: http://nipy.org/nitime
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Timeseries analysis for neuroscience data'

extra:
  recipe-maintainers:
    - arokem
    - ocefpaf
