{% set name = "nitime" %}
{% set version = "0.10.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: "367a15ad2b7a3134dc36ea757beff5bf92681c261cc9cb901f8ac72f35c9b7e6"

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - numpy
    - pip
  run:
    - python
    - cython
    - setuptools
    - matplotlib-base
    - networkx
    - nibabel
    - scipy
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - nitime
    - nitime.algorithms
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://nipy.org/nitime
  summary: 'Nitime: timeseries analysis for neuroscience data'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - arokem
    - ocefpaf
    - effigies
