{% set version = "0.9" %}

package:
  name: nitime
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nitime/nitime-{{ version }}.tar.gz
  sha256: 6e7d90adbb1fa942629bce2f1f9b6de53ea1dd8b0602582ef4608c88d4343874

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - scipy
    - matplotlib-base
    - networkx
    - nibabel

test:
  imports:
    - nitime
    - nitime.algorithms
    - nitime.algorithms.tests
    - nitime.analysis
    - nitime.analysis.tests
    - nitime.fmri
    - nitime.fmri.tests
    - nitime.tests

about:
  home: http://nipy.org/nitime
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Timeseries analysis for neuroscience data

extra:
  recipe-maintainers:
    - arokem
    - ocefpaf
