schema_version: 1

context:
  name: nitime
  version: "0.12.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 12cbf488b0655dc05aa18a0ca5982de970302604e461fc92e87ebd9b7539b6ff

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - cython
        - numpy
    - setuptools_scm
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - cython
    - numpy
    - setuptools_scm
    - setuptools
    - pip
  run:
    - python
    - matplotlib-base
    - networkx
    - nibabel
    - scipy

tests:
  - python:
      imports:
        - nitime
        - nitime.algorithms
        - nitime._utils
  - requirements:
      run:
        - pip
        - pytest
    script:
      - pip check
      - pytest --pyargs nitime

about:
  summary: "Nitime: timeseries analysis for neuroscience data"
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: http://nipy.org/nitime

extra:
  recipe-maintainers:
    - arokem
    - ocefpaf
    - effigies
