travis:
  secure:
    BINSTAR_TOKEN: kQQd4zjbMNXxOxg7avdM1iX48MhGuTuK1nqylKI/deSjLbEYCL9q/2QaECNmhB+Nb1GNWRIRWu7SIleB8vt2ZfHDqg4btac/vZSIjWedmFIIn0jWox/BjcvsLDHciCvtjDRq2t5sIEa5Js2u6ic7hcYiwZj1CG1MC8G2MgGCbvH4TT18aG6pfjfUSJm51uH54eqG8Qy8JMdYAQDuw8FSETLD4FSSMdEyfcjeCzI/LyUKnX2dYzeiQNsNakOKjBpgIeJbKXCdO9BXKZbMrEVqn34+3g+oBxIzNwjrMxwOISUFjzfSxe7srymZIH6SayeAbXKRVFxbXYBm+X5GqHVctUen5kwf2rVbFGLG7W9XopKoVs7eqvlGO0h3Vj05xKiORt4MFGRaB6l5bss1YveXCyd/yu0uB97shzlmphsisvnxWw+P5Lx4Kwd/tGJ0HHMBhZlMesq8VyXLfFYI/FZTjf/pskF/ylyuzdsXP11sOAZs7c9aPxtk8tlv7bRB89dESdjRJ10Nx86jyd9DmE7UeGfwwmG/fJpn6Ka0QzeFl0yeVPs/4otCZxC524/Pbco8UT4ELfAlIb66fRHVs6xMPPEY4vGMbcX4sDO5XPiVMHGyUfAPfj15Bg6X68jtzRor8voY8iLrP8Tpu/n0d8GSv8CXVEeD8m94Z3bhd1beUgg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
