appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: qAe6SCDDycmwqaexAjshp4OI8KfRD/Xj7C5HDFRpYwftf8RVCe6QAKEAOcB0xj1f3Yu5PQamlMrWmw9Sz1bf6jVk3fZdFXeg++/1tOyAYITdyRT4T5YstzlhhoaUljs2ActYAXoFqjJwWrI5pQHOl+pyujNezgO5dhK++XVr7HDynvUJxFbq9xP4YuzDZdfyL+bboRWPef0xfMTaCwExcVSqm/pW+0IHQG17tX6ckCWR3VyTiVO+Kaq4BpdZ9wW+DCFDtI4yp4Bk8xldRgM0a27sMm5Qd7D+DUvCX5jfMTPD7p2Gmfn/ndnLk664tpsdG6vyJvMGlq4qq0H9kjMca3g7VeTfdGIDwxsS2wKr+lWQSMpv834A4dtWGS/JocFxeoYqOKmZbqezakrF4XazZAJ9kah3yfWFk8OMqdlb0VeAin1tKOvOY5zm7JGN8nzPhTeY8AG9W9D50vBWC86QfWSCWedAWUVBZ0CbpfL69MV11b1IEkgi9L6NDTpZYuGD0Wi073E9zxfyB9jquQ6hWqYZf7kpO7eIqfIl4zyzcqCT3WKvlr9pmJVwqwzqVW7BQomngRhxXtgR6rYQ0CoFX6TUZIhp+7AIh8EKQOc6e+m5dCQWKeGnwdFJf2BQcC4LZG4AArXGOZVvLQ5nwzSITZCI90qyGi539F9WtOCG908=}
